import google from "../../../assets/google.svg";
export const JOB_DATA = [
  {
    logo: google,
    title: "Software Engineer",
    company: "Google",
    location: "Mountain View, CA",
    type: "Full Time",
    salary: "$100,000 - $120,000",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, nisl vel tincidunt luctus, nisl nisl aliquam massa, nec lacinia nunc lorem eget massa. Sed euismod, nisl vel tincidunt luctus, nisl nisl aliquam massa, nec lacinia nunc lorem eget massa.",
    requirements: [
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      "Sed euismod, nisl vel tincidunt luctus, nisl nisl aliquam massa, nec lacinia nunc lorem eget massa.",
      "Sed euismod, nisl vel tincidunt luctus, nisl nisl aliquam massa, nec lacinia nunc lorem eget massa.",
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      "Sed euismod, nisl vel tincidunt luctus, nisl nisl aliquam massa, nec lacinia nunc lorem eget massa.",
      "Sed euismod, nisl vel tincidunt luctus, nisl nisl aliquam massa, nec lacinia nunc lorem eget massa.",
    ],
    apply: "https://www.google.com/",
  },
  {
    logo: google,
    title: "Software Engineer",
    company: "Google",
    location: "Mountain View, CA",
    type: "Full Time",
    salary: "$100,000 - $120,000",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, nisl vel tincidunt luctus, nisl nisl aliquam massa, nec lacinia nunc lorem eget massa. Sed euismod, nisl vel tincidunt luctus, nisl nisl aliquam massa, nec lacinia nunc lorem eget massa.",
    requirements: [
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      "Sed euismod, nisl vel tincidunt luctus, nisl nisl aliquam massa, nec lacinia nunc lorem eget massa.",
      "Sed euismod, nisl vel tincidunt luctus, nisl nisl aliquam massa, nec lacinia nunc lorem eget massa.",
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      "Sed euismod, nisl vel tincidunt luctus, nisl nisl aliquam massa, nec lacinia nunc lorem eget massa.",
      "Sed euismod, nisl vel tincidunt luctus, nisl nisl aliquam massa, nec lacinia nunc lorem eget massa.",
    ],
    apply: "https://www.google.com/",
  },
  {
    logo: google,
    title: "Software Engineer",
    company: "Google",
    location: "Mountain View, CA",
    type: "Full Time",
    salary: "$100,000 - $120,000",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, nisl vel tincidunt luctus, nisl nisl aliquam massa, nec lacinia nunc lorem eget massa. Sed euismod, nisl vel tincidunt luctus, nisl nisl aliquam massa, nec lacinia nunc lorem eget massa.",
    requirements: [
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      "Sed euismod, nisl vel tincidunt luctus, nisl nisl aliquam massa, nec lacinia nunc lorem eget massa.",
      "Sed euismod, nisl vel tincidunt luctus, nisl nisl aliquam massa, nec lacinia nunc lorem eget massa.",
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      "Sed euismod, nisl vel tincidunt luctus, nisl nisl aliquam massa, nec lacinia nunc lorem eget massa.",
      "Sed euismod, nisl vel tincidunt luctus, nisl nisl aliquam massa, nec lacinia nunc lorem eget massa.",
    ],
    apply: "https://www.google.com/",
  },
  {
    logo: google,
    title: "Software Engineer",
    company: "Google",
    location: "Mountain View, CA",
    type: "Full Time",
    salary: "$100,000 - $120,000",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, nisl vel tincidunt luctus, nisl nisl aliquam massa, nec lacinia nunc lorem eget massa. Sed euismod, nisl vel tincidunt luctus, nisl nisl aliquam massa, nec lacinia nunc lorem eget massa.",
    requirements: [
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      "Sed euismod, nisl vel tincidunt luctus, nisl nisl aliquam massa, nec lacinia nunc lorem eget massa.",
      "Sed euismod, nisl vel tincidunt luctus, nisl nisl aliquam massa, nec lacinia nunc lorem eget massa.",
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      "Sed euismod, nisl vel tincidunt luctus, nisl nisl aliquam massa, nec lacinia nunc lorem eget massa.",
      "Sed euismod, nisl vel tincidunt luctus, nisl nisl aliquam massa, nec lacinia nunc lorem eget massa.",
    ],
    apply: "https://www.google.com/",
  },
  {
    logo: google,
    title: "Software Engineer",
    company: "Google",
    location: "Mountain View, CA",
    type: "Full Time",
    salary: "$100,000 - $120,000",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, nisl vel tincidunt luctus, nisl nisl aliquam massa, nec lacinia nunc lorem eget massa. Sed euismod, nisl vel tincidunt luctus, nisl nisl aliquam massa, nec lacinia nunc lorem eget massa.",
    requirements: [
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      "Sed euismod, nisl vel tincidunt luctus, nisl nisl aliquam massa, nec lacinia nunc lorem eget massa.",
      "Sed euismod, nisl vel tincidunt luctus, nisl nisl aliquam massa, nec lacinia nunc lorem eget massa.",
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      "Sed euismod, nisl vel tincidunt luctus, nisl nisl aliquam massa, nec lacinia nunc lorem eget massa.",
      "Sed euismod, nisl vel tincidunt luctus, nisl nisl aliquam massa, nec lacinia nunc lorem eget massa.",
    ],
    apply: "https://www.google.com/",
  },
  {
    logo: google,
    title: "Software Engineer",
    company: "Google",
    location: "Mountain View, CA",
    type: "Full Time",
    salary: "$100,000 - $120,000",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, nisl vel tincidunt luctus, nisl nisl aliquam massa, nec lacinia nunc lorem eget massa. Sed euismod, nisl vel tincidunt luctus, nisl nisl aliquam massa, nec lacinia nunc lorem eget massa.",
    requirements: [
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      "Sed euismod, nisl vel tincidunt luctus, nisl nisl aliquam massa, nec lacinia nunc lorem eget massa.",
      "Sed euismod, nisl vel tincidunt luctus, nisl nisl aliquam massa, nec lacinia nunc lorem eget massa.",
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      "Sed euismod, nisl vel tincidunt luctus, nisl nisl aliquam massa, nec lacinia nunc lorem eget massa.",
      "Sed euismod, nisl vel tincidunt luctus, nisl nisl aliquam massa, nec lacinia nunc lorem eget massa.",
    ],
    apply: "https://www.google.com/",
  },
  {
    logo: google,
    title: "Software Engineer",
    company: "Google",
    location: "Mountain View, CA",
    type: "Full Time",
    salary: "$100,000 - $120,000",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, nisl vel tincidunt luctus, nisl nisl aliquam massa, nec lacinia nunc lorem eget massa. Sed euismod, nisl vel tincidunt luctus, nisl nisl aliquam massa, nec lacinia nunc lorem eget massa.",
    requirements: [
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      "Sed euismod, nisl vel tincidunt luctus, nisl nisl aliquam massa, nec lacinia nunc lorem eget massa.",
      "Sed euismod, nisl vel tincidunt luctus, nisl nisl aliquam massa, nec lacinia nunc lorem eget massa.",
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      "Sed euismod, nisl vel tincidunt luctus, nisl nisl aliquam massa, nec lacinia nunc lorem eget massa.",
      "Sed euismod, nisl vel tincidunt luctus, nisl nisl aliquam massa, nec lacinia nunc lorem eget massa.",
    ],
    apply: "https://www.google.com/",
  },
  {
    logo: google,
    title: "Software Engineer",
    company: "Google",
    location: "Mountain View, CA",
    type: "Full Time",
    salary: "$100,000 - $120,000",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, nisl vel tincidunt luctus, nisl nisl aliquam massa, nec lacinia nunc lorem eget massa. Sed euismod, nisl vel tincidunt luctus, nisl nisl aliquam massa, nec lacinia nunc lorem eget massa.",
    requirements: [
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      "Sed euismod, nisl vel tincidunt luctus, nisl nisl aliquam massa, nec lacinia nunc lorem eget massa.",
      "Sed euismod, nisl vel tincidunt luctus, nisl nisl aliquam massa, nec lacinia nunc lorem eget massa.",
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      "Sed euismod, nisl vel tincidunt luctus, nisl nisl aliquam massa, nec lacinia nunc lorem eget massa.",
      "Sed euismod, nisl vel tincidunt luctus, nisl nisl aliquam massa, nec lacinia nunc lorem eget massa.",
    ],
    apply: "https://www.google.com/",
  },
  {
    logo: google,
    title: "Software Engineer",
    company: "Google",
    location: "Mountain View, CA",
    type: "Full Time",
    salary: "$100,000 - $120,000",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, nisl vel tincidunt luctus, nisl nisl aliquam massa, nec lacinia nunc lorem eget massa. Sed euismod, nisl vel tincidunt luctus, nisl nisl aliquam massa, nec lacinia nunc lorem eget massa.",
    requirements: [
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      "Sed euismod, nisl vel tincidunt luctus, nisl nisl aliquam massa, nec lacinia nunc lorem eget massa.",
      "Sed euismod, nisl vel tincidunt luctus, nisl nisl aliquam massa, nec lacinia nunc lorem eget massa.",
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      "Sed euismod, nisl vel tincidunt luctus, nisl nisl aliquam massa, nec lacinia nunc lorem eget massa.",
      "Sed euismod, nisl vel tincidunt luctus, nisl nisl aliquam massa, nec lacinia nunc lorem eget massa.",
    ],
    apply: "https://www.google.com/",
  },
  {
    logo: google,
    title: "Software Engineer",
    company: "Google",
    location: "Mountain View, CA",
    type: "Full Time",
    salary: "$100,000 - $120,000",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, nisl vel tincidunt luctus, nisl nisl aliquam massa, nec lacinia nunc lorem eget massa. Sed euismod, nisl vel tincidunt luctus, nisl nisl aliquam massa, nec lacinia nunc lorem eget massa.",
    requirements: [
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      "Sed euismod, nisl vel tincidunt luctus, nisl nisl aliquam massa, nec lacinia nunc lorem eget massa.",
      "Sed euismod, nisl vel tincidunt luctus, nisl nisl aliquam massa, nec lacinia nunc lorem eget massa.",
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      "Sed euismod, nisl vel tincidunt luctus, nisl nisl aliquam massa, nec lacinia nunc lorem eget massa.",
      "Sed euismod, nisl vel tincidunt luctus, nisl nisl aliquam massa, nec lacinia nunc lorem eget massa.",
    ],
    apply: "https://www.google.com/",
  },
  {
    logo: google,
    title: "Software Engineer",
    company: "Google",
    location: "Mountain View, CA",
    type: "Full Time",
    salary: "$100,000 - $120,000",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, nisl vel tincidunt luctus, nisl nisl aliquam massa, nec lacinia nunc lorem eget massa. Sed euismod, nisl vel tincidunt luctus, nisl nisl aliquam massa, nec lacinia nunc lorem eget massa.",
    requirements: [
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      "Sed euismod, nisl vel tincidunt luctus, nisl nisl aliquam massa, nec lacinia nunc lorem eget massa.",
      "Sed euismod, nisl vel tincidunt luctus, nisl nisl aliquam massa, nec lacinia nunc lorem eget massa.",
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      "Sed euismod, nisl vel tincidunt luctus, nisl nisl aliquam massa, nec lacinia nunc lorem eget massa.",
      "Sed euismod, nisl vel tincidunt luctus, nisl nisl aliquam massa, nec lacinia nunc lorem eget massa.",
    ],
    apply: "https://www.google.com/",
  },
  {
    logo: google,
    title: "Software Engineer",
    company: "Google",
    location: "Mountain View, CA",
    type: "Full Time",
    salary: "$100,000 - $120,000",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, nisl vel tincidunt luctus, nisl nisl aliquam massa, nec lacinia nunc lorem eget massa. Sed euismod, nisl vel tincidunt luctus, nisl nisl aliquam massa, nec lacinia nunc lorem eget massa.",
    requirements: [
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      "Sed euismod, nisl vel tincidunt luctus, nisl nisl aliquam massa, nec lacinia nunc lorem eget massa.",
      "Sed euismod, nisl vel tincidunt luctus, nisl nisl aliquam massa, nec lacinia nunc lorem eget massa.",
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      "Sed euismod, nisl vel tincidunt luctus, nisl nisl aliquam massa, nec lacinia nunc lorem eget massa.",
      "Sed euismod, nisl vel tincidunt luctus, nisl nisl aliquam massa, nec lacinia nunc lorem eget massa.",
    ],
    apply: "https://www.google.com/",
  },
  {
    logo: google,
    title: "Software Engineer",
    company: "Google",
    location: "Mountain View, CA",
    type: "Full Time",
    salary: "$100,000 - $120,000",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, nisl vel tincidunt luctus, nisl nisl aliquam massa, nec lacinia nunc lorem eget massa. Sed euismod, nisl vel tincidunt luctus, nisl nisl aliquam massa, nec lacinia nunc lorem eget massa.",
    requirements: [
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      "Sed euismod, nisl vel tincidunt luctus, nisl nisl aliquam massa, nec lacinia nunc lorem eget massa.",
      "Sed euismod, nisl vel tincidunt luctus, nisl nisl aliquam massa, nec lacinia nunc lorem eget massa.",
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      "Sed euismod, nisl vel tincidunt luctus, nisl nisl aliquam massa, nec lacinia nunc lorem eget massa.",
      "Sed euismod, nisl vel tincidunt luctus, nisl nisl aliquam massa, nec lacinia nunc lorem eget massa.",
    ],
    apply: "https://www.google.com/",
  },
  {
    logo: google,
    title: "Software Engineer",
    company: "Google",
    location: "Mountain View, CA",
    type: "Full Time",
    salary: "$100,000 - $120,000",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, nisl vel tincidunt luctus, nisl nisl aliquam massa, nec lacinia nunc lorem eget massa. Sed euismod, nisl vel tincidunt luctus, nisl nisl aliquam massa, nec lacinia nunc lorem eget massa.",
    requirements: [
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      "Sed euismod, nisl vel tincidunt luctus, nisl nisl aliquam massa, nec lacinia nunc lorem eget massa.",
      "Sed euismod, nisl vel tincidunt luctus, nisl nisl aliquam massa, nec lacinia nunc lorem eget massa.",
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      "Sed euismod, nisl vel tincidunt luctus, nisl nisl aliquam massa, nec lacinia nunc lorem eget massa.",
      "Sed euismod, nisl vel tincidunt luctus, nisl nisl aliquam massa, nec lacinia nunc lorem eget massa.",
    ],
    apply: "https://www.google.com/",
  },
  {
    logo: google,
    title: "Software Engineer",
    company: "Google",
    location: "Mountain View, CA",
    type: "Full Time",
    salary: "$100,000 - $120,000",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, nisl vel tincidunt luctus, nisl nisl aliquam massa, nec lacinia nunc lorem eget massa. Sed euismod, nisl vel tincidunt luctus, nisl nisl aliquam massa, nec lacinia nunc lorem eget massa.",
    requirements: [
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      "Sed euismod, nisl vel tincidunt luctus, nisl nisl aliquam massa, nec lacinia nunc lorem eget massa.",
      "Sed euismod, nisl vel tincidunt luctus, nisl nisl aliquam massa, nec lacinia nunc lorem eget massa.",
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      "Sed euismod, nisl vel tincidunt luctus, nisl nisl aliquam massa, nec lacinia nunc lorem eget massa.",
      "Sed euismod, nisl vel tincidunt luctus, nisl nisl aliquam massa, nec lacinia nunc lorem eget massa.",
    ],
    apply: "https://www.google.com/",
  },
  {
    logo: google,
    title: "Software Engineer",
    company: "Google",
    location: "Mountain View, CA",
    type: "Full Time",
    salary: "$100,000 - $120,000",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, nisl vel tincidunt luctus, nisl nisl aliquam massa, nec lacinia nunc lorem eget massa. Sed euismod, nisl vel tincidunt luctus, nisl nisl aliquam massa, nec lacinia nunc lorem eget massa.",
    requirements: [
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      "Sed euismod, nisl vel tincidunt luctus, nisl nisl aliquam massa, nec lacinia nunc lorem eget massa.",
      "Sed euismod, nisl vel tincidunt luctus, nisl nisl aliquam massa, nec lacinia nunc lorem eget massa.",
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      "Sed euismod, nisl vel tincidunt luctus, nisl nisl aliquam massa, nec lacinia nunc lorem eget massa.",
      "Sed euismod, nisl vel tincidunt luctus, nisl nisl aliquam massa, nec lacinia nunc lorem eget massa.",
    ],
    apply: "https://www.google.com/",
  },
  {
    logo: google,
    title: "Software Engineer",
    company: "Google",
    location: "Mountain View, CA",
    type: "Full Time",
    salary: "$100,000 - $120,000",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, nisl vel tincidunt luctus, nisl nisl aliquam massa, nec lacinia nunc lorem eget massa. Sed euismod, nisl vel tincidunt luctus, nisl nisl aliquam massa, nec lacinia nunc lorem eget massa.",
    requirements: [
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      "Sed euismod, nisl vel tincidunt luctus, nisl nisl aliquam massa, nec lacinia nunc lorem eget massa.",
      "Sed euismod, nisl vel tincidunt luctus, nisl nisl aliquam massa, nec lacinia nunc lorem eget massa.",
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      "Sed euismod, nisl vel tincidunt luctus, nisl nisl aliquam massa, nec lacinia nunc lorem eget massa.",
      "Sed euismod, nisl vel tincidunt luctus, nisl nisl aliquam massa, nec lacinia nunc lorem eget massa.",
    ],
    apply: "https://www.google.com/",
  },
  {
    logo: google,
    title: "Software Engineer",
    company: "Google",
    location: "Mountain View, CA",
    type: "Full Time",
    salary: "$100,000 - $120,000",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, nisl vel tincidunt luctus, nisl nisl aliquam massa, nec lacinia nunc lorem eget massa. Sed euismod, nisl vel tincidunt luctus, nisl nisl aliquam massa, nec lacinia nunc lorem eget massa.",
    requirements: [
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      "Sed euismod, nisl vel tincidunt luctus, nisl nisl aliquam massa, nec lacinia nunc lorem eget massa.",
      "Sed euismod, nisl vel tincidunt luctus, nisl nisl aliquam massa, nec lacinia nunc lorem eget massa.",
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      "Sed euismod, nisl vel tincidunt luctus, nisl nisl aliquam massa, nec lacinia nunc lorem eget massa.",
      "Sed euismod, nisl vel tincidunt luctus, nisl nisl aliquam massa, nec lacinia nunc lorem eget massa.",
    ],
    apply: "https://www.google.com/",
  },
  {
    logo: google,
    title: "Software Engineer",
    company: "Google",
    location: "Mountain View, CA",
    type: "Full Time",
    salary: "$100,000 - $120,000",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, nisl vel tincidunt luctus, nisl nisl aliquam massa, nec lacinia nunc lorem eget massa. Sed euismod, nisl vel tincidunt luctus, nisl nisl aliquam massa, nec lacinia nunc lorem eget massa.",
    requirements: [
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      "Sed euismod, nisl vel tincidunt luctus, nisl nisl aliquam massa, nec lacinia nunc lorem eget massa.",
      "Sed euismod, nisl vel tincidunt luctus, nisl nisl aliquam massa, nec lacinia nunc lorem eget massa.",
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      "Sed euismod, nisl vel tincidunt luctus, nisl nisl aliquam massa, nec lacinia nunc lorem eget massa.",
      "Sed euismod, nisl vel tincidunt luctus, nisl nisl aliquam massa, nec lacinia nunc lorem eget massa.",
    ],
    apply: "https://www.google.com/",
  },
  {
    logo: google,
    title: "Software Engineer",
    company: "Google",
    location: "Mountain View, CA",
    type: "Full Time",
    salary: "$100,000 - $120,000",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, nisl vel tincidunt luctus, nisl nisl aliquam massa, nec lacinia nunc lorem eget massa. Sed euismod, nisl vel tincidunt luctus, nisl nisl aliquam massa, nec lacinia nunc lorem eget massa.",
    requirements: [
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      "Sed euismod, nisl vel tincidunt luctus, nisl nisl aliquam massa, nec lacinia nunc lorem eget massa.",
      "Sed euismod, nisl vel tincidunt luctus, nisl nisl aliquam massa, nec lacinia nunc lorem eget massa.",
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      "Sed euismod, nisl vel tincidunt luctus, nisl nisl aliquam massa, nec lacinia nunc lorem eget massa.",
      "Sed euismod, nisl vel tincidunt luctus, nisl nisl aliquam massa, nec lacinia nunc lorem eget massa.",
    ],
    apply: "https://www.google.com/",
  },
];
